### ISSUE TITLE
Introduce OpenTelemetry Java Agent into FulfillmentService

### ISSUE THREAD

**Issue by mreider** [mreider/burger-shop#7]
This will be the only service fully instrumented with the Java OpenTelemetry Agent. You can read more about it here:

https://github.com/open-telemetry/opentelemetry-java-instrumentation?tab=readme-ov-file#configuring-the-agent

- Export JVM metrics, Traces, and application logs (stdout / stderr) to the Dynatrace OTLP endpoint.
- I think this should work here, but this might be for traces only? https://docs.dynatrace.com/docs/extend-dynatrace/opentelemetry/walkthroughs/java/java-auto

This should work within the Kubernetes cluster because of these secrets, which I load as environment variables into the pods.

```
kubectl -n burger-shop create secret generic dynatrace-secrets --from-literal="dynatrace_token=(redacted)" --from-literal="dynatrace_endpoint=https://bmm59542.dev.dynatracelabs.com"
```

In the deployment YAML for the Fulfillment Service:
```
env:
        - name: DYNATRACE_TOKEN
          valueFrom:
            secretKeyRef:
              name: dynatrace-secrets
              key: dynatrace_token
        - name: DYNATRACE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: dynatrace-secrets
              key: dynatrace_endpoint
```
